animals=(f"Wolves,Foxes,Dogs")
print("Wolves are one of the most dangerous predators in the forest")
print("Foxes are known to be really fast on their four feet")
print("Dogs can be very good pets once you take care of them enough")
print("All of those animals have great agility and speed")
