tuple=("Salad, Fries, Burgers, Pizza, Steak")
print(f"Salad")
print(f"Fries")
print(f"Burgers")
print(f"Pizza")
print(f"Steak")
tuple=("Salad, Fries, Burgers, Chicken, Burritos")
print(f"Chicken")
print(f"Burritos")