describe_restaurant=()
print(f"The restaurant name is Arby's and it's cuisine type is Thai")
open_restaurant=()
print(f"Thai is now open")
describe_restaurant=()
print(f"The restaurant name is Ihop and the cuisine type is also Indian")
open_restaurant=()
print(f"Ihop should be opening soon")
describe_restaurant=()
print(f"Outback Steakhouse is the name and the cuisine type is Italian")
open_restaurant=()
print(f"The Steakhouse will have service tomorrow")